# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cac02fe042c05393091853cec6c09038d3dc6a1a20aece8ce7f382cb1e93ccce7a07d925cd50eb06da3a67afd3e52fc9c692586cfd6b7235cb36b722645031b

test:
  secret_key_base: 15376a6933e471b54c360aca8eff5291c74bb7dfd66812dd01d9d24e253849778b03e70aa6fd15081870afc602672982abddd2aa8395004d27eaf75c748144d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
